apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubernetes-udacity-demo
  region: eu-west-2

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 1
    volumeSize: 80